name: Update Garden Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    uses: prjctimg/profile/.github/workflows/update.yml@v1
    with:
      commit-message: "tending the garden"
      git-user-name: "iseeheaven"
      git-user-email: "iseeheaven@outlook.com"
    secrets: inherit
